### ISSUE TITLE
Normalize file paths between POSIX and Windows

### ISSUE THREAD

**Issue by koterpillar** [coveralls-clients/coveralls-python#159] opened 2017-07-22 06:57 UTC
I am running builds for https://github.com/aloetesting/aloe on Travis CI and AppVeyor (for Windows). On Windows, directory and file names are separated by a backslash (\), everywhere else it is a forward slash (/).

Coveralls should normalize the paths coming from different build systems to properly merge the files coverage.

**Comment by TheKevJames** [comment] 2017-08-27 10:17
Thanks for the report! I'll put this on my backlog. PRs are always welcome, as well :)

Sort-of a duplicate of #118.

**Comment by TheKevJames** [comment] 2018-08-31 05:11
@koterpillar this issue should now be resolved as of [release 1.5.0](https://github.com/coveralls-clients/coveralls-python/releases/tag/1.5.0).

**Closed** 2018-08-31 05:11 UTC
Labels: type:bug
