### ISSUE TITLE
Coveralls Appveyor Path Issue

### ISSUE THREAD

**Issue by jborean93** [coveralls-clients/coveralls-python#118] opened 2016-08-31 11:50 UTC
Hi

I am trying to get coveralls to work with my appveyor build and have been successful in getting the data posted to appveyor. The issue I have is in coveralls the paths are in windows format which it cannot then parse correctly. I cannot use it to view the lines that are covered on the coveralls website. An example of what happens is shown below.

![image](https://cloud.githubusercontent.com/assets/8462645/18127515/3244d42a-6fc4-11e6-9a14-233cfa7b171c.png)

It looks like coveralls is trying to find the files in the format folder\file instead of folder/file and the HTML path it uses doesn't work.

I have run it with debug and have attached it [coveralls debug.txt](https://github.com/coagulant/coveralls-python/files/447104/coveralls.debug.txt)

Thanks

Jordan

**Comment by TheKevJames** [comment] 2017-08-27 10:18
Closing as a sort-of-duplicate of #159, but I do appreciate the report!

**Closed by TheKevJames** 2017-08-27 10:18 UTC

**Comment by TheKevJames** [comment] 2018-08-31 05:12
@jborean93 @RazerM @thatslch this issue should now be resolved as of [release 1.5.0](https://github.com/coveralls-clients/coveralls-python/releases/tag/1.5.0).
