### ISSUE TITLE
Failure when using --finish option

### ISSUE THREAD

**Issue by caleb15** [coveralls-clients/coveralls-python#234] opened 2020-08-06 17:36 UTC
`venv/bin/coveralls --finish`

```
Finishing parallel jobs...
Parallel finish failed: No build matching CI build number  found
Traceback (most recent call last):
  File "/home/********/project/venv/lib/python3.7/site-packages/coveralls/cli.py", line 80, in main
    coverallz.parallel_finish()
  File "/home/********/project/venv/lib/python3.7/site-packages/coveralls/api.py", line 236, in parallel_finish
    raise CoverallsException('Parallel finish failed: {}'.format(e))
coveralls.exception.CoverallsException: Parallel finish failed: No build matching CI build number  found
```

**Comment by caleb15** [comment] 2020-08-06 17:36
will be fixed by https://github.com/coveralls-clients/coveralls-python/pull/233

**Comment by TheKevJames** [comment] 2020-08-10 23:10
Closing as a dupe of #234

**Comment by TheKevJames** [comment] 2020-08-10 23:10
Er, #235, my bad.

**Closed by TheKevJames** 2020-08-10 23:10 UTC
